import type { PlkgEdge, PlkgNode } from "@sbud-d/types";

import { DEMO_STUDENT_ID, demoSubjects } from "../academic/academic.fixtures.js";
import { demoDocuments } from "../documents/document.fixtures.js";

const CREATED_AT = "2026-07-12T00:00:00.000Z";

export const demoPlkgNodes: PlkgNode[] = [
  ...demoSubjects.map((subject): PlkgNode => ({
    id: `plkg-subject-${subject.id}`,
    studentId: DEMO_STUDENT_ID,
    subjectId: subject.id,
    type: "subject",
    label: subject.name,
    description: `${subject.code} subject knowledge area.`,
    learningStatus: subject.progressPercent >= 10 ? "learning" : "introduced",
    confidenceLevel: subject.progressPercent,
    masteryScore: subject.progressPercent,
    sourceType: "academic_profile",
    sourceId: subject.id,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  })),
  {
    id: "plkg-topic-functions",
    studentId: DEMO_STUDENT_ID,
    subjectId: "subject-programming",
    type: "topic",
    label: "Functions and control flow",
    description: "Current programming topic introduced from the academic subject context.",
    learningStatus: "learning",
    confidenceLevel: 32,
    masteryScore: 28,
    sourceType: "academic_profile",
    sourceId: "subject-programming",
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    id: "plkg-concept-recursion",
    studentId: DEMO_STUDENT_ID,
    subjectId: "subject-programming",
    type: "concept",
    label: "Recursion",
    description: "A function-solving pattern where a problem is reduced into smaller calls.",
    learningStatus: "needs_review",
    confidenceLevel: 20,
    masteryScore: 18,
    sourceType: "blie_interaction",
    sourceId: "sprint-6-chat",
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    id: "plkg-topic-limits",
    studentId: DEMO_STUDENT_ID,
    subjectId: "subject-calculus",
    type: "topic",
    label: "Limits and continuity",
    description: "Current calculus topic introduced from academic subject context.",
    learningStatus: "introduced",
    confidenceLevel: 18,
    masteryScore: 15,
    sourceType: "academic_profile",
    sourceId: "subject-calculus",
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  ...demoDocuments.slice(0, 1).map((document): PlkgNode => ({
    id: `plkg-resource-${document.id}`,
    studentId: DEMO_STUDENT_ID,
    subjectId: document.subjectId,
    type: "resource",
    label: document.title,
    description: document.summary,
    learningStatus: "understanding",
    confidenceLevel: 45,
    masteryScore: 40,
    sourceType: "document",
    sourceId: document.id,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  })),
];

export const demoPlkgEdges: PlkgEdge[] = [
  {
    id: "plkg-edge-programming-functions",
    studentId: DEMO_STUDENT_ID,
    sourceNodeId: "plkg-subject-subject-programming",
    targetNodeId: "plkg-topic-functions",
    type: "contains",
    label: "Programming contains functions and control flow.",
    strength: 0.8,
    createdAt: CREATED_AT,
  },
  {
    id: "plkg-edge-functions-recursion",
    studentId: DEMO_STUDENT_ID,
    sourceNodeId: "plkg-topic-functions",
    targetNodeId: "plkg-concept-recursion",
    type: "requires",
    label: "Recursion requires confidence with functions.",
    strength: 0.9,
    createdAt: CREATED_AT,
  },
  {
    id: "plkg-edge-document-functions",
    studentId: DEMO_STUDENT_ID,
    sourceNodeId: "plkg-resource-document-database-lecture",
    targetNodeId: "plkg-topic-functions",
    type: "explains",
    label: "Lecture material explains functions.",
    strength: 0.7,
    createdAt: CREATED_AT,
  },
  {
    id: "plkg-edge-calculus-limits",
    studentId: DEMO_STUDENT_ID,
    sourceNodeId: "plkg-subject-subject-calculus",
    targetNodeId: "plkg-topic-limits",
    type: "contains",
    label: "Calculus contains limits and continuity.",
    strength: 0.8,
    createdAt: CREATED_AT,
  },
];
